- hosts: application-servers
  gather_facts: True
  become: yes
  become_method: sudo

  tasks:

  - name: Ensure hostname set
    hostname: name={{ inventory_hostname }}

  - name: "install python3"
    apt:
      name: ['python']
      state: latest

  

# vim:ft=ansible:
